# Generated by Django 3.2.4 on 2021-07-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='executor',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='service_type',
            new_name='order_type',
        ),
    ]
